import type { Metadata } from "next";
import "./globals.scss";
import { noto_serif } from "@/app/lib/fonts";
import Header from "@/app/ui/header/Header";
import Footer from "@/app/ui/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${noto_serif.className} flex h-screen flex-col overflow-hidden bg-white text-dark`}
      >
        <Header />
        <div className="mx-2 mb-2 flex flex-grow flex-col overflow-hidden sm:mx-6 sm:mb-6">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
