"use client";

import type { Metadata } from "next";
import { createClient } from "next-sanity";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = createClient({
    projectId: "kcartf0h",
    dataset: "production",
    apiVersion: "2023-12-04",
    useCdn: true,
  });

  const query = `*[_type == "post"]`;
  const posts = await client.fetch(query);

  console.log(posts[0]);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
